---
- name: "APT: install dependencies"
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
      - curl
    state: present

- name: "APT: see if we have a keyring"
  stat:
    path: /etc/apt/trusted.gpg.d/mariadb-keyring.pgp
  register: keyring_exists

- name: "APT: fetch keyring"
  ansible.builtin.get_url:
    url: https://mariadb.org/mariadb_release_signing_key.pgp
    dest: /etc/apt/trusted.gpg.d/mariadb-keyring.pgp
    mode: "644"
  when: not keyring_exists.stat.exists
  register: keyring

- name: "APT: Import Key"
  shell: "apt-key add /etc/apt/trusted.gpg.d/mariadb-keyring.pgp"
  when: keyring.changed

- name: "APT: Install mariadb repository"
  template:
    src: mariadb.sources.j2
    dest: /etc/apt/sources.list.d/mariadb-keyring.pgp
    owner: root
    mode: "644"
  register: repo

- name: "APT: Update cache"
  ansible.builtin.apt:
    update_cache: true
  when: repo.changed

- name: "APT: Install mariadb"
  ansible.builtin.apt:
    pkg:
      - "mariadb-server"
      - "python3-pymysql"
    state: present

- name: "APT: install cluster dependencies"
  ansible.builtin.apt:
    pkg:
      - "mariadb-backup"
      - "socat"
    state: present

- name: Create mysql tmp directory
  file:
    path: /var/lib/mysql-tmp
    state: directory
    owner: mysql
    group: mysql
    mode: 0750
  notify: "{{ 'mariadb_restart' if not mariadb_bootstrap|default(false) else 'noop' }}"

- name: "UFW: enable or disable mariadb port depending on if external access is allowed"
  community.general.ufw:
    rule: allow
    port: "3306"
    proto: tcp
  when: mariadb_external_access|default(false) or mariadb_cluster|default(false)

- name: "UFW: enable galera replication"
  community.general.ufw:
    rule: allow
    port: "4567"
    proto: tcp
  when: mariadb_cluster|default(false)

- name: "UFW: enable galera IST"
  community.general.ufw:
    rule: allow
    port: "4568"
    proto: tcp
  when: mariadb_cluster|default(false)

- name: "UFW: enable galera SST"
  community.general.ufw:
    rule: allow
    port: "4444"
    proto: tcp
  when: mariadb_cluster|default(false)

